### ISSUE TITLE
CLI Interface

### ISSUE THREAD

**Issue by houfu** [houfu/redlines#11]
A command line interface might be an interesting and relatively straightforward implementation.

As an additional way to use the code, this might be good for quick tests and comparing plain text files.

https://github.com/Textualize/rich can be used to display rich markup in the terminal.

**Comment by houfu** [comment]
Hmm first screenshots look pretty nice.

![Screenshot from 2023-05-28 16-52-56](https://github.com/houfu/redlines/assets/19525701/61668e84-cb27-491a-8f6e-7e391f866724)

![Screenshot from 2023-05-28 16-54-27](https://github.com/houfu/redlines/assets/19525701/d5c072b6-1474-4502-a7b3-9f0d13c4d70c)

Any comments? I am still considering whether a simple statistics panel might be useful.

**Comment by HRNPH** [comment]
the percentage change should be counted from
the character changed/all characters
