### ISSUE TITLE
Styling doesn't work in Colab

### ISSUE THREAD

**Issue by houfu** [houfu/redlines#20]
I've added notes on how to get your styling to show in environments such as Streamlit and Github. See #17 

Now you can add Colab to this list. The main issue is some environments do not render HTML code found in markdown, and the markdown standard is not consistent in showing deletions and insertions.

Currently, the only way to make it work is to set the `markdown_style` argument in Redlines as "none".

TODO: Update the documentation to reflect what we can do for Colab.

**Comment by bkowshik** [comment]
### output_rich

This looks as expected on Google Colab.

```python
Redlines('This is an expariment.', 'This is an experiment', markdown_style=None).output_rich
```

<img width="288" alt="Screenshot 2023-08-27 at 20 06 36" src="https://github.com/houfu/redlines/assets/2899501/d3e1dee2-262c-41b0-af18-40a96880b39b">

### output_markdown

This does not render properly though.

```python
Redlines('This is an expariment.', 'This is an experiment').output_markdown
This is an <span style='color:red;font-weight:700;text-decoration:line-through;'>expariment.</span><span style='color:green;font-weight:700;'>experiment</span>
```

<img width="221" alt="Screenshot 2023-08-27 at 20 11 33" src="https://github.com/houfu/redlines/assets/2899501/3a8c5c4c-267a-4efe-9853-4878d6a83e42">

```python
Markdown(Redlines('This is an expariment.', 'This is an experiment', markdown_style=None).output_markdown)
```

Adding the `markdown_style=None` did not help either. It looks exactly the same as before.

**Comment by houfu** [comment]
Woah I wasn't aware that output_rich works in Colab. We should put that down too.

I couldn't reproduce `None` not working though. Here's my test colab notebook: https://colab.research.google.com/drive/1RrpeKylF5UjB2X3g6qyXnZyp2to1cLQX?usp=sharing

I don't use Colab often enough, so maybe I am missing something. Maybe your environment is set up differently?

**Comment by bkowshik** [comment]
This is what I meant, the code snippet below gives me the following output:

```python
test = Redlines('This is an expariment.', 'This is an experiment')
display(Markdown(test.output_markdown))
```

<img width="224" alt="Screenshot 2023-08-29 at 23 38 53" src="https://github.com/houfu/redlines/assets/2899501/deaf043a-fbfa-4412-81f7-088cdb539dad">

**Comment by houfu** [comment]
OK that's expected because colab disregards any HTML code.

This one works though. Does it work for you @bkowshik ?
![image](https://github.com/houfu/redlines/assets/19525701/0632c1cd-7e74-4cfa-a461-0ff694522417)

**Comment by bkowshik** [comment]
Yes,  this works for me on Google Colab. Why is `markdown_style` taking `"none"` (string) instead of `None`?

**Comment by houfu** [comment]
Interesting. My original thought was that "none" was a style, not that it was not a style. The default (iirc) is "red-green", so I don't expect someone to pass `None`

**Comment by houfu** [comment]
Docs now suggest what to do for colab: https://houfu.github.io/redlines/redlines/redlines.html#colab
