### ISSUE TITLE
cli.py truncates long strings

### ISSUE THREAD

**Issue by jeisner** [houfu/redlines#37]
Only 6 lines are shown in the CLI output.
Can this be expanded for long outputs, either automatically or by command-line options?

**Comment by houfu** [comment]
Hi sorry, I haven't touched the cli part of this for a while, since I was also considering the status of a related project: https://github.com/houfu/redlines-textual

But can I check your use case? Are you talking about long outputs (like just a few more lines) or really long outputs.

**Comment by jeisner** [comment]
Thanks for the pointer to the related project. 

 I think redlines CLI is more useful for shorter text that can be compared at the terminal or in a bash_kernel notebook cell.  

(To compare versions of longer documents, a diff tool seems more appropriate - it usually lets you jump from change to change   Although there are times that you just want to read the long document, for example in `less`, and have a little extra markup along the way, showing what's new.)

When I posted this issue, I was using redlines at the terminal to compare LLM outputs under different prompts. These outputs can vary in length; in my case they were several sentences.  I ended up writing my own simpler version of the script, which worked fine.

**Comment by houfu** [comment]
Thanks! It seems that unlike textual, rich doesn't easily have scrollbars in their panels. So it looks like it will be a limitation for now. 
But I thought your script made sense so I made it a new command.
I wrote the code, but I hope you don't mind if I credit you for it.

**Comment by jeisner** [comment]
As you like.  
Although to prevent a profusion of CLIs, I wonder this should just be an option to your existing script?
(I could also imagine the existing script warning of truncation, when it happens, and recommending the option.)
