### ISSUE TITLE
Is Redlines no longer compatible with 3.8 and likely below that?

### ISSUE THREAD

**Issue by servient-ashwin** [houfu/redlines#42]
Hey,

The recent release seem to have broken the redlines library for people who do not have `>=3.9` Python. The reason being Python 3.9 or greater likely uses "different" syntax than the versions before like for example

Python 3.9 : `list[str]`
Python 3.8 : `List[str]  `

but this is not used consistently throughout the code
for example

```
class Chunk:
    """A chunk of text that is being compared. In some cases, it may be the whole document"""

    text: List[str]

```

and all other places where a combination of the package `typing` and 3.9's typing is used.

There is no quick fix other than downgrading to 0.4.2 or lower, is there a plan to change that? I would assume something like creating custom types and using them based on the system version, or releasing python specific versions using `project.toml` . I may be overreaching here since this is a a preliminary root cause find at the moment given the above data.

**Comment by houfu** [comment]
* Python 3.8 shouldn't be dropped
* The class Chunk is 0.5.0 code.
* Lemme release a hotfix.

Thanks for reporting!
